export const products = [
  {
    name: "Sports Essentials Logo Gloves",
    slug: "sports-essentials-logo-gloves",
    category: "Gloves",
    price: 25,
    description:
      "Carry on with your workout when cold weather arrives. These all-cotton gloves have a polar fleece lining so that wind and cold won't bring your workout to an early end. Ribbed cuffs provide a secure fit.",
    brand: "Reebok",
    sizes: ["M", "L"],
    onSale: true,
    bestSeller: false,
    images: ["gloves2-pic1", "gloves2-pic2"],
    available: true,
  },
  {
    name: "Comfort Fleece 3.0 Gloves",
    category: "Gloves",
    slug: "comfort-fleece-gloves",
    price: 30,
    description:
      "These gloves keep you warm through cold-weather commutes and afternoons on the slope. They have breathable insulation and smart moisture-wicking features so you stay warm and dry. The palm is designed to give you good grip, and there are touchscreen-friendly points on the thumb and forefinger.",
    brand: "Adidas",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: true,
    images: ["gloves1-pic1", "gloves1-pic2"],
    available: true,
  },
  {
    name: "Freak 5.0 Polynesian Bowl Gloves",
    slug: "freak-polynesian-bowl-gloves",
    category: "Gloves",
    price: 60,
    description:
      "The perfect blend of impact protection and dexterity. These adidas football receiver gloves are padded across the backhand and wrist, giving you a controlled, steady feel. They're ergonomically built to mimic the hand's natural movement. This pair celebrates the Polynesian Bowl with graphics on the backhand and palm.",
    brand: "Adidas",
    sizes: ["M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["gloves3-pic1", "gloves3-pic2", "gloves3-pic3"],
    available: true,
  },
  {
    name: "OS Run Gloves",
    slug: "os-run-gloves",
    category: "Gloves",
    price: 25,
    description:
      "Chilled fingers don't have to be a part of your winter running routine. These running gloves are made of lightweight and breathable fabric to keep your hands covered on those frosty mornings. Reflective details help you stand out.",
    brand: "Reebok",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["gloves4-pic1", "gloves4-pic2"],
    available: false,
  },

  {
    name: "Superlite Hat",
    slug: "superlite-hat",
    category: "Hats & Beanies",
    price: 24,
    description:
      "When the sun's blazing, you've got to dress accordingly. Top off your warm-weather workout ensemble with the adidas Superlite Hat. The comfortable, six-panel construction has perforated side panels to help keep you cool. A non-glare undervisor makes running on bright concrete easy on the eyes.",
    brand: "Adidas",
    sizes: ["M"],
    onSale: false,
    bestSeller: false,
    images: ["hat1-pic1", "hat1-pic2"],
    available: false,
  },
  {
    name: "Classics Foundation Bucket Hat",
    slug: "classics-foundation-bucket-hat",
    category: "Hats & Beanies",
    price: 28,
    description:
      "Worn by fishermen and farmers since the 1900s, the bucket hat never goes out of style. Wear this low-key look rain or shine to top off your easygoing wardrobe. A contrast Vector logo on the band keeps it sporty.",
    brand: "Reebok",
    sizes: ["S", "M", "L"],
    onSale: true,
    bestSeller: false,
    images: ["hat2-pic1", "hat2-pic2"],
    available: true,
  },
  {
    name: "Rib Cuff Beanie",
    slug: "rib-cuff-beanie",
    category: "Hats & Beanies",
    price: 24,
    description:
      "Low temperatures, questionable hair day, pulling a look together — with this adidas beanie, all reasons are good reasons for tossing it on. It's low-key enough to not distract, and more than comfortable enough to get you from morning to night feeling good all the way through.",
    brand: "Adidas",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["hat3-pic1", "hat3-pic2", "hat3-pic3"],
    available: true,
  },
  {
    name: "Baseball Cap",
    slug: "baseball-cap",
    category: "Hats & Beanies",
    price: 40,
    description:
      "Pull together any casual outfit. This adidas baseball cap lets you do just that. The Trefoil and 3-Stripes are decked out in colorful rhinestones, giving your look the perfect pop of sparkle. While you shine in the light, the pre-curved brim helps keep the sun out of your eyes.",
    brand: "Adidas",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["hat4-pic1", "hat4-pic2", "hat4-pic3"],
    available: false,
  },
  {
    name: "Classics Foundation Beanie",
    slug: "classics-foundation-beanie",
    category: "Hats & Beanies",
    price: 20,
    description:
      "Keep your look chill in crisp weather in this beanie. A subtle logo patch on the cuff stays true to heritage style. The clean, minimalist design pairs well with everything.",
    brand: "Reebok",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["hat5-pic1", "hat5-pic2"],
    available: false,
  },
  {
    name: "United By Fitness Baseball Hat",
    slug: "united-by-fitness-baseball-hat",
    category: "Hats & Beanies",
    price: 28,
    description:
      "You don't just do one sport on the weekend. Sometimes you fit in a round of golf, a workout and a run. The Speedwick sweatband in this Reebok hat wicks moisture away, so you stay cool and dry no matter what you're doing. Eyelets on the hat add an extra hit of breathability.",
    brand: "Reebok",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["hat6-pic1", "hat6-pic2"],
    available: false,
  },
  {
    name: "Adidas Adventure Top Loader Bag",
    slug: "adventurer-top-loader-bag",
    category: "Bags & Backpacks",
    price: 110,
    description:
      "Take it back to the '90s, but without those uncomfortable, external frame backpacks. Comfort is key with this adidas backpack. Made from durable, recycled polyester ripstop, it's got a padded back and adjustable shoulder straps to make carrying comfortable. So go ahead, load it up. Multiple compartments and compression straps on the sides make adventuring easy.",
    brand: "Adidas",
    sizes: ["M"],
    onSale: false,
    bestSeller: false,
    images: ["bag1-pic1", "bag1-pic2", "bag1-pic3"],
    available: true,
  },
  {
    name: "National Backpack",
    slug: "national-backpack",
    category: "Bags & Backpacks",
    price: 40,
    description:
      "Stash, zip, go. You've got just what you need for the day ahead, thanks to your adidas backpack. Water bottle, ear buds, even your laptop. All stowed away and easily within reach.",
    brand: "Adidas",
    sizes: ["M"],
    onSale: false,
    bestSeller: true,
    images: ["bag2-pic1", "bag2-pic2"],
    available: true,
  },
  {
    name: "Workout Ready Grip Bag",
    slug: "workout-ready-grip-bag",
    category: "Bags & Backpacks",
    price: 30,
    description:
      "You and your friends are finally going to get away for more than just a few hours. This Reebok bag holds enough gear to handle whatever adventures you get up to. Sling it over your shoulder while you decide who sits where in the car. Wear it like a backpack as you hike over to your little cabin.",
    brand: "Reebok",
    sizes: ["M"],
    onSale: false,
    bestSeller: false,
    images: ["bag3-pic1", "bag3-pic2"],
    available: false,
  },
  {
    name: "Classics Supporter Backpack",
    slug: "classics-supporter-backpack",
    category: "Bags & Backpacks",
    price: 35,
    description:
      "Show your love of sport in this fan-inspired backpack. The Vector design has been reimagined with a triangle design inspired by the supporter flag. Zip pockets keep your essentials organized. The straps adjust for extra comfort.",
    brand: "Reebok",
    sizes: ["M"],
    onSale: true,
    bestSeller: false,
    images: ["bag4-pic1", "bag4-pic2"],
    available: true,
  },
  {
    name: "Treefoil No-Show Socks 6 Pairs",
    slug: "treefoil-noshow-socks-six-pairs",
    category: "Socks",
    price: 20,
    description:
      "These no-show socks have a durable build and a classic look. They're made with a cushioned footbed and sweat-wicking fabric.",
    brand: "Adidas",
    sizes: ["M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["socks1-pic1", "socks1-pic2"],
    available: true,
  },
  {
    name: "Treefoil Crew Socks 6 Pairs",
    slug: "treefoil-crew-socks-six-pairs",
    category: "Socks",
    price: 20,
    description:
      "Clean, sporty style for every day. These men's Trefoil crew socks have a durable build with added cushioning and sweat-wicking fabric for comfort. The handy six-pack will see you through the week.",
    brand: "Adidas",
    sizes: ["M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["socks2-pic1", "socks2-pic2"],
    available: true,
  },
  {
    name: "Classics Fold-Over Crew Socks 3 Pairs",
    slug: "classics-fold-over-crew-socks-three-pairs",
    category: "Socks",
    price: 15,
    description:
      "Work out or hang out in these comfortable crew socks. A fold-over cuff lets you adjust the look and fit. The heel and toe are reinforced with terry for extra cushioning. Each pack includes two plain pairs and one graphic pair of socks.",
    brand: "Reebok",
    sizes: ["S", "M", "L"],
    onSale: false,
    bestSeller: false,
    images: ["socks3-pic1", "socks3-pic2"],
    available: true,
  },
  {
    name: "Adidas Face Covers 3-Pack",
    slug: "adidas-face-covers-three-pack",
    category: "Face Covers",
    price: 20,
    description:
      "Made with soft, breathable fabric the adidas Face Cover is comfortable, washable and reusable for practicing healthy habits every day. This cover is not a medically-graded mask nor personal protective equipment.",
    brand: "Adidas",
    sizes: ["S", "M"],
    onSale: false,
    bestSeller: false,
    images: ["mask1-pic1", "mask1-pic2"],
    available: true,
  },
  {
    name: "Reebok Face Covers 3-Pack",
    slug: "reebok-face-covers-three-pack",
    category: "Face Covers",
    price: 15,
    description:
      "Made with soft, breathable fabric the Reebok Face Cover is comfortable, washable and reusable for practicing healthy habits every day. This cover is not a medically graded mask nor a Personal Protective Equipment but can help prevent the spread of viruses and germs through droplet transmission.",
    brand: "Reebok",
    sizes: ["S", "M"],
    onSale: false,
    bestSeller: true,
    images: ["mask2-pic1", "mask2-pic2"],
    available: true,
  },
  {
    name: "Antique Black Injected SP0047",
    slug: "antique-black-injected",
    category: "Sunglasses",
    price: 140,
    description:
      "Classic sunglasses made to satisfy your every need. Suitable for everyday use, parties, work, travel - the sky is the limit!",
    brand: "Adidas",
    sizes: ["M"],
    onSale: false,
    bestSeller: false,
    images: ["sunglasses1-pic1", "sunglasses1-pic2", "sunglasses1-pic3"],
    available: true,
  },
  {
    name: "Off White Injected SP0043",
    slug: "off-white-injected",
    category: "Sunglasses",
    price: 128,
    description:
      "Cool sunglasses made from extremely high quality material which is virtually unbreakable. Appropriate to use in every environment - guaranteed to make you look like the coolest guy in the room!",
    brand: "Adidas",
    sizes: ["M"],
    onSale: false,
    bestSeller: true,
    images: ["sunglasses2-pic1", "sunglasses2-pic2", "sunglasses2-pic3"],
    available: true,
  },
  {
    name: "Originals Sunglasses OR0038",
    slug: "originals-sunglasses",
    category: "Sunglasses",
    price: 80,
    description:
      "A classic style with fresh updates, these adidas sunglasses have an iconic cat-eye frame. Logos and Colorful enamel detailing adds a touch of flash. The end tips can be adjusted for outstanding comfort.",
    brand: "Adidas",
    sizes: ["M"],
    onSale: true,
    bestSeller: false,
    images: ["sunglasses3-pic1", "sunglasses3-pic2", "sunglasses3-pic3"],
    available: true,
  },
  {
    name: "Steel Metal Bottle 1L",
    slug: "steel-metal-bottle",
    category: "Water Bottles",
    price: 25,
    description:
      "Take your hot or cold beverages to go. This bottle has a double-wall construction, so that coffee you got in the morning will still be warm after lunch. It has a hook on the top, so you can clip it to your gym bag before heading to a training session.",
    brand: "Adidas",
    sizes: ["M"],
    onSale: false,
    bestSeller: false,
    images: ["bottle1-pic1", "bottle1-pic2"],
    available: true,
  },
  {
    name: "Reebok Aluminum Water Bottle",
    slug: "reebok-aluminium-water-bottle",
    category: "Water Bottles",
    price: 30,
    description:
      "Hydration is your key to fitness greatness. Keep H2O on hand with this go-everywhere bottle. The aluminum construction ensures long lasting durability, and the folding mouth piece makes sipping your fuel a cinch. Plus, the convenient carry handle adds an easy grab-and-go element.",
    brand: "Reebok",
    sizes: ["M"],
    onSale: false,
    bestSeller: false,
    images: ["bottle2-pic1", "bottle2-pic2"],
    available: true,
  },
];
